Added refresh button
pagopa/interop-fe-probing pull request #12
Opened 2023-04-14 14:31 UTC by AlessandroColucci

2023-04-17 13:14 UTC, Carminepo2 approved these changes

2023-04-18 07:55 UTC, Carminepo2 requested changes

2023-04-18 07:55 UTC, Carminepo2 commented on src/components/monitoringTable/MonitoringTable.tsx
> +            sx={{ float: 'right' }}
Il `float: 'right'` può essere rimosso, il componente `Filters` si occupa del layout.

2023-04-18 08:28 UTC, Carminepo2 approved these changes

2023-04-18 08:36 UTC, ruggerocastagnola approved these changes

2023-04-18 08:37 UTC, merged