Feature/iesp 191
pagopa/interop-fe-probing pull request #22
Opened 2023-05-26 14:12 UTC by epetkova2

Login and logout implementations

2023-05-30 07:28 UTC, Carminepo2 requested changes
Ciao! Inizia con questi punti, poi ci ritorno una volta che l'ho provata in locale

2023-05-30 07:28 UTC, Carminepo2 commented on src/authetication/storage.tsx
> +export { setStorage, deleteStorage, resetStorage, getStorage };
C'è un motivo per la quale le operazioni sul session storage sono wrappate in delle promise?

2023-05-30 07:28 UTC, Carminepo2 commented on src/authetication/auth.tsx
> +}
Qui utilizzerei la sintassi di async/await, se non ci fosse un motivo valido, toglierei "l'asincronia" della funzione `setStorage`.

2023-05-30 07:28 UTC, Carminepo2 commented on src/authetication/auth.tsx
> +    })
Anche qui, stessa cosa di sopra

2023-05-30 14:09 UTC, Carminepo2 requested changes

2023-05-31 07:51 UTC, Carminepo2 approved these changes

2023-05-31 10:16 UTC, ruggerocastagnola approved these changes

2023-05-31 10:24 UTC, merged