Feature/iesp 197
pagopa/interop-fe-probing pull request #26
Opened 2023-06-07 13:04 UTC by epetkova2

reset password page

2023-06-12 15:04 UTC, Carminepo2 requested changes

2023-06-13 12:56 UTC, Carminepo2 requested changes

2023-06-13 12:56 UTC, Carminepo2 commented on src/components/forms/passwordResetForm/PasswordResetForm.tsx
> + * password validation regex
Intendevo qualcosa di più descrittivo. 
Quali controlli effettua sulla stringa? Una lunghezza minima di caratteri? Quanti? La presenza di caratteri speciali? Quali?

2023-06-13 13:15 UTC, Carminepo2 approved these changes

2023-06-13 13:37 UTC, ruggerocastagnola approved these changes

2023-06-13 13:40 UTC, merged