Feature/fix default grafico
pagopa/interop-fe-probing pull request #32
Opened 2023-07-04 09:01 UTC by AlessandroColucci

Nuova implementazione grafico, fix default filtri e fix bug sul controllo del token alla seconda login.

2023-07-10 07:20 UTC, Carminepo2 requested changes

2023-07-10 07:20 UTC, Carminepo2 commented on src/components/charts/lineChart/LineChart.tsx
> +    : new Date()
Renderei più leggibili questi due blocchi di ternari

2023-07-11 07:05 UTC, Carminepo2 approved these changes

2023-07-11 08:44 UTC, ruggerocastagnola approved these changes

2023-07-11 10:49 UTC, ruggerocastagnola approved these changes

2023-07-11 10:50 UTC, Carminepo2 approved these changes

2023-07-11 11:32 UTC, merged