Feature/IESP-79
pagopa/interop-fe-probing pull request #4
Opened 2023-03-28 08:23 UTC by AlessandroColucci

Scaffhold of the project

2023-03-28 10:34 UTC, Carminepo2 requested changes

2023-03-28 10:34 UTC, Carminepo2 commented on src/pages/ErrorPage.tsx
> +        <Typography variant="body1" sx={{ color: "#17324D" }}>
Il color qui non serve, di default il testo è già di quel colore.

2023-03-28 10:34 UTC, Carminepo2 commented on src/components/header/Header.tsx
> +};
Anche qui, se non ci sono particolari motivi, non è necessario avvolgere i componenti nelle griglie. Aggiungeremmo un tag `header` per questioni di accessibilità:

2023-03-28 10:34 UTC, Carminepo2 commented on src/components/header/Header.tsx
> +};
```suggestion
    <header>
      <HeaderAccount
        enableAssistanceButton={false}
        loggedUser={false}
        rootLink={link}
        onAssistanceClick={() => {
          console.log("Clicked/Tapped on Assistance");
        }}
      />
      <HeaderProduct productsList={productsList} />
    </header>
  );
};
```

2023-03-28 10:34 UTC, Carminepo2 commented on src/components/footer/Footer.tsx
> +    />
mui-italia non avvolge direttamente il componente `Footer` nel tag html footer, consigliamo di farlo qui:

```suggestion
    <footer>
      <Footer
        loggedUser={false}
        languages={lngs}
        onLanguageChanged={() => {}}
        companyLink={pagoPALink}
        postLoginLinks={postLoginLinks}
        preLoginLinks={preLoginLinks}
        currentLangCode="it"
        onExit={(exitAction) => {
          console.log("Executing exit Action");
          exitAction();
        }}
        productsJsonUrl="https://dev.selfcare.pagopa.it/assets/products.json"
        hideProductsColumn={false}
        legalInfo={
          <span>
            <strong>PagoPA S.p.A.</strong> - Società per azioni con socio unico - Capitale sociale di euro 1,000,000
            interamente versato - Sede legale in Roma, Piazza Colonna 370, CAP 00187 - N. di iscrizione a Registro
            Imprese di Roma, CF e P.IVA 15376371009
          </span>
        }
      />
    </footer>
```

2023-03-28 13:02 UTC, Carminepo2 commented on src/App.tsx
> +        open={stores.useSpinnerStore((state: SpinnerType) => state.activated)}
Questi tipi non sono necessari il server di typescript li inferisce automaticamente. Valutate voi, è solo per semplificare

2023-03-28 13:22 UTC, AlessandroColucci commented on src/App.tsx
> +        open={stores.useSpinnerStore((state: SpinnerType) => state.activated)}
Hai ragione scusami, credevo che nello scorso commento volessi che io li specificassi. Comunque va bene, li rimuovo così da semplificare.

2023-03-28 16:07 UTC, ruggerocastagnola approved these changes

2023-03-28 16:07 UTC, ruggerocastagnola approved these changes

2023-03-29 08:09 UTC, Carminepo2 approved these changes

2023-03-29 08:14 UTC, merged